/**
 * bitsandbolts-themes — build.js
 *
 * Reads design tokens from tokens/ and generates platform-specific outputs:
 *   dist/web/{theme}/light.css, dark.css       — CSS custom properties
 *   dist/android/{theme}/LightColors.kt        — Compose lightColorScheme
 *   dist/android/{theme}/DarkColors.kt         — Compose darkColorScheme
 *   dist/react-native/{theme}/light.ts         — typed constants
 *   dist/react-native/{theme}/dark.ts
 *
 * Usage:
 *   pnpm build
 *   ANDROID_PACKAGE=com.myapp pnpm build   (sets package in Kotlin output)
 *
 * Run from repo root. Requires Node 18+.
 */

import StyleDictionary from 'style-dictionary';

const THEMES = ['cloud', 'ocean', 'slate', 'robot', 'bitsandbolts'];
const MODES  = ['light', 'dark'];
const ANDROID_PACKAGE = process.env.ANDROID_PACKAGE || 'REPLACE_ME';

// ─── Custom Format: Kotlin Color Scheme ──────────────────────────────────────

StyleDictionary.registerFormat({
  name: 'kotlin/color-scheme',
  format: ({ dictionary, options }) => {
    const { theme, mode } = options;
    const ThemeName  = theme.charAt(0).toUpperCase() + theme.slice(1);
    const ModeName   = mode.charAt(0).toUpperCase() + mode.slice(1);
    const schemeType = mode === 'light' ? 'lightColorScheme' : 'darkColorScheme';

    // M3 ColorScheme only accepts these standard roles; extra tokens become standalone vals.
    const M3_ROLES = new Set([
      'primary','onPrimary','primaryContainer','onPrimaryContainer',
      'secondary','onSecondary','secondaryContainer','onSecondaryContainer',
      'tertiary','onTertiary','tertiaryContainer','onTertiaryContainer',
      'background','onBackground',
      'surface','onSurface','surfaceVariant','onSurfaceVariant','surfaceTint',
      'inversePrimary','inverseSurface','inverseOnSurface',
      'error','onError','errorContainer','onErrorContainer',
      'outline','outlineVariant','scrim',
    ]);

    const colorTokens  = dictionary.allTokens.filter(t => t.path[0] === 'color');
    const opacityTokens = dictionary.allTokens.filter(t => t.path[0] === 'opacity');
    const m3Tokens     = colorTokens.filter(t => M3_ROLES.has(t.path[1]));
    const extraTokens  = colorTokens.filter(t => !M3_ROLES.has(t.path[1]));
    const val = t => t.value ?? t.$value;
    const toPascal = parts => parts.map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('');

    const toKotlin = hex => `Color(0xFF${hex.replace('#', '').toUpperCase()})`;
    const consts   = colorTokens.map(t => `private val _${t.path[1]} = ${toKotlin(val(t))}`).join('\n');
    const entries  = m3Tokens.map(t => `    ${t.path[1]} = _${t.path[1]}`).join(',\n');
    const extraColorVals = extraTokens.map(t => `val ${ThemeName}${ModeName}${t.path[1].charAt(0).toUpperCase() + t.path[1].slice(1)} = _${t.path[1]}`);
    const extraOpacityVals = opacityTokens.map(t => {
      const name = toPascal(t.path.slice(1));
      return `val ${ThemeName}${ModeName}${name} = ${parseFloat(val(t)).toFixed(2)}f`;
    });
    const allExtras = [...extraColorVals, ...extraOpacityVals];
    const extras   = allExtras.length ? `\n${allExtras.join('\n')}` : '';

    return `// Auto-generated by bitsandbolts-themes — do not edit
// Theme: ${ThemeName} / Mode: ${ModeName}
//
// To set your package name, run:
//   ANDROID_PACKAGE=com.yourapp pnpm build
// or find-and-replace REPLACE_ME after copying.
package ${ANDROID_PACKAGE}.ui.theme.generated

import androidx.compose.material3.${schemeType}
import androidx.compose.ui.graphics.Color

${consts}

val ${ThemeName}${ModeName}ColorScheme = ${schemeType}(
${entries}
)
${extras}
`;
  },
});

// ─── Custom Format: TypeScript / React Native ─────────────────────────────────

StyleDictionary.registerFormat({
  name: 'typescript/react-native',
  format: ({ dictionary, options }) => {
    const { theme, mode } = options;

    const colorTokens    = dictionary.allTokens.filter(t => t.path[0] === 'color');
    const spacingTokens  = dictionary.allTokens.filter(t => t.path[0] === 'spacing');
    const radiusTokens   = dictionary.allTokens.filter(t => t.path[0] === 'radius');
    const fontSizeTokens = dictionary.allTokens.filter(t => t.path[0] === 'font' && t.path[1] === 'size');
    const fontWtTokens   = dictionary.allTokens.filter(t => t.path[0] === 'font' && t.path[1] === 'weight');
    const fontFamTokens  = dictionary.allTokens.filter(t => t.path[0] === 'font' && t.path[1] === 'family');

    const v     = t => t.value ?? t.$value;
    const toNum = t => parseFloat(v(t));
    const colFmt  = colorTokens.map(t => `  ${t.path[1]}: '${v(t)}'`).join(',\n');
    const spFmt   = spacingTokens.map(t => `  '${t.path[1]}': ${toNum(t)}`).join(',\n');
    const radFmt  = radiusTokens.map(t => `  '${t.path[1]}': ${toNum(t)}`).join(',\n');
    const fsFmt   = fontSizeTokens.map(t => `  '${t.path[2]}': ${toNum(t)}`).join(',\n');
    const fwFmt   = fontWtTokens.map(t => `  '${t.path[2]}': '${v(t)}'`).join(',\n');
    const ffFmt   = fontFamTokens.map(t => `  ${t.path[2]}: '${v(t)}'`).join(',\n');

    return `// Auto-generated by bitsandbolts-themes — do not edit
// Theme: ${theme} / Mode: ${mode}
// Note: font files must be bundled in your app — see README.

export const colors = {
${colFmt}
} as const;

export const spacing = {
${spFmt}
} as const;

export const radii = {
${radFmt}
} as const;

export const fontSize = {
${fsFmt}
} as const;

export const fontWeight = {
${fwFmt}
} as const;

export const fontFamily = {
${ffFmt}
} as const;
`;
  },
});

// ─── Build ────────────────────────────────────────────────────────────────────

for (const theme of THEMES) {
  for (const mode of MODES) {
    const modeName = mode.charAt(0).toUpperCase() + mode.slice(1);
    const selector = mode === 'light' ? ':root' : '[data-theme="dark"]';

    const sd = new StyleDictionary({
      source: [
        'tokens/base/**/*.json',
        `tokens/themes/${theme}/${mode}.json`,
      ],
      platforms: {
        // CSS custom properties — import in Tauri/Vue or any web project
        web: {
          transformGroup: 'css',
          prefix: 'bb',
          buildPath: `dist/web/${theme}/`,
          files: [{
            destination: `${mode}.css`,
            format: 'css/variables',
            options: { selector, outputReferences: false },
          }],
        },

        // Kotlin color scheme — copy to ui/theme/generated/ in Android project
        android: {
          transforms: ['attribute/cti'],
          buildPath: `dist/android/${theme}/`,
          files: [{
            destination: `${modeName}Colors.kt`,
            format: 'kotlin/color-scheme',
            filter: token => token.path[0] === 'color' || token.path[0] === 'opacity',
            options: { theme, mode },
          }],
        },

        // TypeScript constants — import in React Native or Expo project
        reactNative: {
          transformGroup: 'js',
          buildPath: `dist/react-native/${theme}/`,
          files: [{
            destination: `${mode}.ts`,
            format: 'typescript/react-native',
            options: { theme, mode },
          }],
        },
      },
    });

    await sd.buildAllPlatforms();
    process.stdout.write(`  [${theme}/${mode}] done\n`);
  }
}

// ─── Copy static components to dist ─────────────────────────────────────────
import {
  readdirSync,
  copyFileSync,
  mkdirSync,
  existsSync,
  readFileSync,
  writeFileSync,
  statSync,
} from 'fs';
import { join } from 'path';

function copyDirRecursive(srcDir, destDir, pathLabel) {
  if (!existsSync(srcDir)) return;
  mkdirSync(destDir, { recursive: true });
  for (const entry of readdirSync(srcDir)) {
    const srcPath = join(srcDir, entry);
    const destPath = join(destDir, entry);
    if (statSync(srcPath).isDirectory()) {
      copyDirRecursive(srcPath, destPath, pathLabel ? `${pathLabel}/${entry}` : entry);
      continue;
    }
    copyFileSync(srcPath, destPath);
    process.stdout.write(`  [${pathLabel ? `${pathLabel}/` : ''}${entry}] done\n`);
  }
}

const COMPONENTS_SRC  = 'components';
const COMPONENTS_DIST = 'dist/web/components';
mkdirSync(COMPONENTS_DIST, { recursive: true });
for (const file of readdirSync(COMPONENTS_SRC)) {
  if (file.endsWith('.css')) {
    copyFileSync(join(COMPONENTS_SRC, file), join(COMPONENTS_DIST, file));
    process.stdout.write(`  [components/${file}] done\n`);
  }
}

// Copy icon assets to dist for use in apps
const ICONS_SRC  = 'assets/icons';
const ICONS_DIST = 'dist/web/icons';
mkdirSync(ICONS_DIST, { recursive: true });
for (const file of readdirSync(ICONS_SRC)) {
  if (file.endsWith('.svg')) {
    copyFileSync(join(ICONS_SRC, file), join(ICONS_DIST, file));
    process.stdout.write(`  [icons/${file}] done\n`);
  }
}

copyDirRecursive('assets/brand', 'dist/web/brand', 'brand');

// Copy static Android Kotlin sources to dist/android/
// These use REPLACE_ME as a package placeholder; dev.sh substitutes the real package.
const ANDROID_STATIC_SRC  = 'android';
const ANDROID_STATIC_DIST = 'dist/android';
mkdirSync(ANDROID_STATIC_DIST, { recursive: true });
for (const file of readdirSync(ANDROID_STATIC_SRC)) {
  if (file.endsWith('.kt')) {
    copyFileSync(join(ANDROID_STATIC_SRC, file), join(ANDROID_STATIC_DIST, file));
    process.stdout.write(`  [android/${file}] done\n`);
  }
}

// Copy bundled Android TTF fonts to dist/android/fonts/
const ANDROID_FONTS_SRC  = 'assets/android-fonts';
const ANDROID_FONTS_DIST = 'dist/android/fonts';
mkdirSync(ANDROID_FONTS_DIST, { recursive: true });
for (const file of readdirSync(ANDROID_FONTS_SRC)) {
  if (file.endsWith('.ttf')) {
    copyFileSync(join(ANDROID_FONTS_SRC, file), join(ANDROID_FONTS_DIST, file));
    process.stdout.write(`  [android/fonts/${file}] done\n`);
  }
}

// Copy Android vector drawables to dist/android/drawables/
const ANDROID_DRAWABLES_DIST = 'dist/android/drawables';
mkdirSync(ANDROID_DRAWABLES_DIST, { recursive: true });
for (const file of readdirSync(ICONS_SRC)) {
  if (file.endsWith('.xml')) {
    copyFileSync(join(ICONS_SRC, file), join(ANDROID_DRAWABLES_DIST, file));
    process.stdout.write(`  [android/drawables/${file}] done\n`);
  }
}

// Copy locally bundled fonts to dist so apps never need to fetch from network
const FONTS_SRC  = 'fonts';
const FONTS_DIST = 'dist/web/fonts';
mkdirSync(FONTS_DIST, { recursive: true });
for (const file of readdirSync(FONTS_SRC)) {
  copyFileSync(join(FONTS_SRC, file), join(FONTS_DIST, file));
  process.stdout.write(`  [fonts/${file}] done\n`);
}

const WEB_FONTS_SRC = 'assets/web-fonts';
if (existsSync(WEB_FONTS_SRC)) {
  for (const file of readdirSync(WEB_FONTS_SRC)) {
    copyFileSync(join(WEB_FONTS_SRC, file), join(FONTS_DIST, file));
    process.stdout.write(`  [web-fonts/${file}] done\n`);
  }
}

console.log('\n✓ All themes built successfully.');
console.log(`  dist/web/           CSS custom properties + components + icons`);
console.log(`  dist/android/       Kotlin Color Schemes (package: ${ANDROID_PACKAGE})`);
console.log(`  dist/react-native/  TypeScript constants`);

// ─── Per-theme icon config ────────────────────────────────────────────────────
for (const theme of THEMES) {
  const iconsFile = `tokens/themes/${theme}/icons.json`;
  const icons = existsSync(iconsFile)
    ? JSON.parse(readFileSync(iconsFile, 'utf8'))
    : { family: 'material-symbols', style: 'filled' };

  // Web: CSS custom properties consumed by BbIcon.vue
  writeFileSync(`dist/web/${theme}/icons.css`,
    `/* Auto-generated by bitsandbolts-themes build.js — do not edit */\n` +
    `:root {\n` +
    `  --bb-icon-family: ${icons.family};\n` +
    `  --bb-icon-style: ${icons.style};\n` +
    `}\n`);
  process.stdout.write(`  [${theme}/icons.css] done\n`);

  // Android: Kotlin icon object with resolved filled/outlined ImageVectors
  const ThemeName    = theme[0].toUpperCase() + theme.slice(1);
  const composeStyle = icons.style === 'filled' ? 'Filled' : 'Outlined';
  writeFileSync(`dist/android/${theme}/IconStyle.kt`,
    `// Auto-generated by bitsandbolts-themes — do not edit\n` +
    `// Theme: ${ThemeName} / Icon style: ${icons.style}\n` +
    `package ${ANDROID_PACKAGE}.ui.theme.generated\n\n` +
    `import androidx.compose.material.icons.Icons\n` +
    `import androidx.compose.material.icons.filled.*\n` +
    `import androidx.compose.material.icons.outlined.*\n` +
    `import androidx.compose.material.icons.automirrored.filled.*\n` +
    `import androidx.compose.material.icons.automirrored.outlined.*\n` +
    `import androidx.compose.ui.graphics.vector.ImageVector\n\n` +
    `object ${ThemeName}Icons {\n` +
    `    val Settings:      ImageVector = Icons.${composeStyle}.Settings\n` +
    `    val CloudUpload:   ImageVector = Icons.${composeStyle}.CloudUpload\n` +
    `    val CloudDownload: ImageVector = Icons.${composeStyle}.CloudDownload\n` +
    `    val ArrowBack:     ImageVector = Icons.AutoMirrored.${composeStyle}.ArrowBack\n` +
    `    val Person:        ImageVector = Icons.${composeStyle}.Person\n` +
    `    val Logout:        ImageVector = Icons.AutoMirrored.${composeStyle}.ExitToApp\n` +
    `    val Devices:       ImageVector = Icons.${composeStyle}.Devices\n` +
    `    val Smartphone:    ImageVector = Icons.${composeStyle}.Smartphone\n` +
    `    val Computer:      ImageVector = Icons.${composeStyle}.Computer\n` +
    `    val Visibility:    ImageVector = Icons.${composeStyle}.Visibility\n` +
    `    val VisibilityOff: ImageVector = Icons.${composeStyle}.VisibilityOff\n` +
    `    val Lock:          ImageVector = Icons.${composeStyle}.Lock\n` +
    `    val MarkEmailRead: ImageVector = Icons.${composeStyle}.MarkEmailRead\n` +
    `}\n`);
  process.stdout.write(`  [${theme}/IconStyle.kt] done\n`);
}
